# Generated by Django 5.1.4 on 2025-06-29 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_cat', models.TextField(blank=True, null=True)),
                ('estado_cat', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('fecha_creacion_cat', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_cat', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id_ent', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion_ent', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_ent', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id_temp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_temp', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio_temp', models.DateField(blank=True, null=True)),
                ('fecha_fin_temp', models.DateField(blank=True, null=True)),
                ('fecha_creacion_temp', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_temp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id_tip', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tip', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_tip', models.TextField(blank=True, null=True)),
                ('estado_tip', models.BooleanField(default=True)),
                ('fecha_creacion_tip', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_tip', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadEscala',
            fields=[
                ('id_unes', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unes', models.CharField(max_length=50, unique=True)),
                ('descripcion_unes', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_unes', models.BooleanField(default=True)),
                ('fecha_creacion_unes', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_unes', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equ', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_equ', models.TextField(blank=True, null=True)),
                ('logo_equ', models.ImageField(blank=True, null=True, upload_to='equipos/')),
                ('fecha_fundado_equ', models.DateField(blank=True, null=True)),
                ('fecha_creacion_equ', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_equ', models.DateTimeField(blank=True, null=True)),
                ('categorias', models.ManyToManyField(blank=True, to='Entrenamientos.categoria')),
                ('fk_id_ent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Entrenamientos.entrenador')),
                ('fk_id_temp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Entrenamientos.temporada')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id_jug', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento_jug', models.DateField(blank=True, null=True)),
                ('edad_jug', models.IntegerField(blank=True, null=True)),
                ('peso_jug', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altura_jug', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('posicion_jug', models.CharField(blank=True, max_length=50, null=True)),
                ('pie_dominante_jug', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_representante_jug', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_emergencia_jug', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_ingreso_jug', models.DateField(blank=True, null=True)),
                ('fecha_creacion_jug', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_jug', models.DateTimeField(blank=True, null=True)),
                ('fk_id_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.categoria')),
                ('fk_id_ent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.entrenador')),
                ('fk_id_equ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id_pru', models.AutoField(primary_key=True, serialize=False)),
                ('macro_pru', models.CharField(max_length=10)),
                ('promedio_pru', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones_pru', models.TextField(blank=True, null=True)),
                ('estado_pru', models.BooleanField(default=True)),
                ('fecha_pru', models.DateField(blank=True, null=True)),
                ('fecha_creacion_pru', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_pru', models.DateTimeField(blank=True, null=True)),
                ('fk_id_ent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.entrenador')),
                ('fk_id_jug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.jugador')),
                ('fk_id_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.temporada')),
                ('fk_id_tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.tipoevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroEvaluacion',
            fields=[
                ('id_prm', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prm', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_prm', models.TextField(blank=True, null=True)),
                ('estado_prm', models.BooleanField(default=True)),
                ('fecha_creacion_prm', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_prm', models.DateTimeField(blank=True, null=True)),
                ('fk_tipo_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.tipoevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='EscalaEvaluacion',
            fields=[
                ('id_escala', models.AutoField(primary_key=True, serialize=False)),
                ('valoroptimo_escala', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_escala', models.CharField(choices=[('inversa', 'Inversa'), ('directa', 'Directa')], max_length=10)),
                ('unidad_escala', models.CharField(max_length=100)),
                ('fecha_creacion_escala', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_escala', models.DateTimeField(blank=True, null=True)),
                ('fk_id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.categoria')),
                ('fk_id_prm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.parametroevaluacion')),
                ('fk_id_tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.tipoevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('id_rub', models.AutoField(primary_key=True, serialize=False)),
                ('valor_min_rub', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_max_rub', models.DecimalField(decimal_places=2, max_digits=6)),
                ('puntaje_rub', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estado_rub', models.BooleanField(default=True)),
                ('fecha_creacion_rub', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_rub', models.DateTimeField(blank=True, null=True)),
                ('fk_id_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.categoria')),
                ('fk_id_prm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.parametroevaluacion')),
                ('fk_id_unes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.unidadescala')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usu', models.AutoField(primary_key=True, serialize=False)),
                ('correo_usu', models.CharField(max_length=150, unique=True)),
                ('cedula_usu', models.CharField(max_length=15, unique=True)),
                ('telefono_usu', models.CharField(blank=True, max_length=20, null=True)),
                ('primer_apellido_usu', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido_usu', models.CharField(blank=True, max_length=100, null=True)),
                ('nombres_usu', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_usu', models.TextField(blank=True, null=True)),
                ('estado_invitacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('activado', 'Activado')], default='pendiente', max_length=10)),
                ('estado_usu', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('rol_usu', models.CharField(choices=[('admin_dios', 'Admin Dios'), ('admin', 'Administrador'), ('entrenador', 'Entrenador'), ('jugador', 'Jugador')], max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion_usu', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_usu', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TokenPassword',
            fields=[
                ('id_tok', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('expiracion_tok', models.DateTimeField(blank=True, null=True)),
                ('usado_tok', models.BooleanField(default=False)),
                ('fecha_creacion_tok', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_tok', models.DateTimeField(blank=True, null=True)),
                ('fk_id_usu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jugador',
            name='fk_id_usu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='fk_id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrenador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PromedioGeneralEvaluacion',
            fields=[
                ('id_promgen', models.AutoField(primary_key=True, serialize=False)),
                ('macro_promgen', models.CharField(max_length=10)),
                ('promedio_promgen', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion_promgen', models.DateTimeField(auto_now_add=True)),
                ('fk_id_jug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.jugador')),
                ('fk_id_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.temporada')),
            ],
            options={
                'unique_together': {('fk_id_jug', 'fk_id_temp', 'macro_promgen')},
            },
        ),
        migrations.CreateModel(
            name='PromedioTipoEvaluacion',
            fields=[
                ('id_promtipo', models.AutoField(primary_key=True, serialize=False)),
                ('macro_promtipo', models.CharField(max_length=10)),
                ('promedio_promtipo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion_promtipo', models.DateTimeField(auto_now_add=True)),
                ('fk_id_jug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.jugador')),
                ('fk_id_temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.temporada')),
                ('fk_id_tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.tipoevaluacion')),
            ],
            options={
                'unique_together': {('fk_id_jug', 'fk_id_tip', 'fk_id_temp', 'macro_promtipo')},
            },
        ),
    ]
