# Generated by Django 5.1.4 on 2025-05-29 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion_cat', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_cat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion_ent', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_ent', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_eva', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_eva', models.TextField(blank=True, null=True)),
                ('fecha_creacion_eva', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_eva', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_temp', models.DateField(blank=True, null=True)),
                ('fecha_fin_temp', models.DateField(blank=True, null=True)),
                ('fecha_creacion_temp', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_temp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equ', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_equ', models.TextField(blank=True, null=True)),
                ('logo_equ', models.TextField(blank=True, null=True)),
                ('fecha_fundado_equ', models.DateField(blank=True, null=True)),
                ('fecha_creacion_equ', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_equ', models.DateTimeField(auto_now=True)),
                ('fk_id_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Entrenamientos.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_jug', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_apellido_jug', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido_jug', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento_jug', models.DateField(blank=True, null=True)),
                ('edad_jug', models.IntegerField(blank=True, null=True)),
                ('numero_jug', models.IntegerField(blank=True, null=True)),
                ('peso_jug', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('altura_jug', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('posicion_jug', models.CharField(blank=True, max_length=50, null=True)),
                ('pie_dominante_jug', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_representante_jug', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_emergencia_jug', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_ingreso_jug', models.DateField(blank=True, null=True)),
                ('fecha_creacion_jug', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_jug', models.DateTimeField(auto_now=True)),
                ('fk_id_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Entrenamientos.categoria')),
                ('fk_id_ent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Entrenamientos.entrenador')),
                ('fk_id_equ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Entrenamientos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_pru', models.CharField(blank=True, max_length=10, null=True)),
                ('observaciones_pru', models.TextField(blank=True, null=True)),
                ('fecha_pru', models.DateField(blank=True, null=True)),
                ('fecha_creacion_pru', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_pru', models.DateTimeField(auto_now=True)),
                ('fk_id_ent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Entrenamientos.entrenador')),
                ('fk_id_eva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Entrenamientos.evaluacion')),
                ('fk_id_jug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Entrenamientos.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_det', models.CharField(blank=True, max_length=100, null=True)),
                ('valoracion_det', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion_det', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_det', models.DateTimeField(auto_now=True)),
                ('fk_id_pru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Entrenamientos.prueba')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usu', models.AutoField(primary_key=True, serialize=False)),
                ('correo_usu', models.CharField(max_length=150, unique=True)),
                ('cedula_usu', models.CharField(max_length=15, unique=True)),
                ('primer_apellido_usu', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido_usu', models.CharField(blank=True, max_length=100, null=True)),
                ('nombres_usu', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_usu', models.TextField(blank=True, null=True)),
                ('rol_usu', models.CharField(choices=[('admin_dios', 'Admin Dios'), ('admin', 'Administrador'), ('entrenador', 'Entrenador'), ('jugador', 'Jugador')], max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion_usu', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_usu', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TokenPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('expiracion_tok', models.DateTimeField(blank=True, null=True)),
                ('usado_tok', models.BooleanField(default=False)),
                ('fecha_creacion_tok', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_tok', models.DateTimeField(auto_now=True)),
                ('fk_id_usu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entrenador',
            name='fk_id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ResultadoMacro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macro_resul', models.CharField(blank=True, max_length=10, null=True)),
                ('habilidad_balon_resul', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('defensa_resul', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mental_resul', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pase_resul', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promedio_general', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion_resul', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_resul', models.DateTimeField(auto_now=True)),
                ('fk_id_jug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Entrenamientos.jugador')),
            ],
            options={
                'unique_together': {('fk_id_jug', 'macro_resul')},
            },
        ),
    ]
