# Generated by Django 5.1.4 on 2025-05-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado_invitacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activado', 'Activado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_usu',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_usu',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
