# Generated by Django 5.1.4 on 2025-06-29 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePrueba',
            fields=[
                ('id_detpru', models.AutoField(primary_key=True, serialize=False)),
                ('valor_observado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad', models.CharField(blank=True, max_length=30, null=True)),
                ('nota_calculada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_creacion_detpru', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_detpru', models.DateTimeField(blank=True, null=True)),
                ('fk_id_prm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.parametroevaluacion')),
                ('fk_id_pru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Entrenamientos.prueba')),
            ],
        ),
    ]
