# Generated by Django 5.1.4 on 2025-06-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0002_detalleprueba'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promediotipoevaluacion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='promediotipoevaluacion',
            name='fk_id_jug',
        ),
        migrations.RemoveField(
            model_name='promediotipoevaluacion',
            name='fk_id_temp',
        ),
        migrations.RemoveField(
            model_name='promediotipoevaluacion',
            name='fk_id_tip',
        ),
        migrations.AlterUniqueTogether(
            name='prueba',
            unique_together={('fk_id_jug', 'fk_id_tip', 'fk_id_temp', 'macro_pru')},
        ),
        migrations.DeleteModel(
            name='PromedioGeneralEvaluacion',
        ),
        migrations.DeleteModel(
            name='PromedioTipoEvaluacion',
        ),
    ]
