# Generated by Django 5.1.4 on 2025-06-01 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0002_usuario_estado_invitacion_usuario_estado_usu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='fk_id_usu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
