# Generated by Django 5.1.4 on 2025-06-01 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0003_jugador_fk_id_usu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='fk_id_cat',
        ),
        migrations.AddField(
            model_name='categoria',
            name='fk_id_equ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Entrenamientos.equipo'),
            preserve_default=False,
        ),
    ]
