# Generated by Django 5.1.4 on 2025-07-01 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0003_alter_promediotipoevaluacion_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromedioJugador',
            fields=[
                ('id_proju', models.AutoField(primary_key=True, serialize=False)),
                ('macro_proju', models.CharField(max_length=20)),
                ('promedio_proju', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_calculo_proju', models.DateTimeField(auto_now_add=True)),
                ('jugador_proju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.jugador')),
                ('temporada_proju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.temporada')),
                ('tipo_proju', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.tipoevaluacion')),
            ],
        ),
    ]
