# Generated by Django 5.1.4 on 2025-06-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0004_remove_equipo_fk_id_cat_categoria_fk_id_equ'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='fk_id_equ',
        ),
        migrations.AddField(
            model_name='equipo',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='Entrenamientos.categoria'),
        ),
    ]
