# Generated by Django 5.1.4 on 2025-06-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0005_remove_categoria_fk_id_equ_equipo_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion_cat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='estado_cat',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
    ]
