# Generated by Django 5.1.4 on 2025-06-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0006_categoria_descripcion_cat_categoria_estado_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='logo_equ',
            field=models.ImageField(blank=True, null=True, upload_to='equipos/'),
        ),
    ]
