# Generated by Django 5.1.4 on 2025-06-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0007_alter_equipo_logo_equ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_actualizacion_equ',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
