# Generated by Django 5.1.4 on 2025-06-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0008_alter_equipo_fecha_actualizacion_equ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='fecha_actualizacion_cat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleprueba',
            name='fecha_actualizacion_det',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='fecha_actualizacion_ent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha_actualizacion_eva',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='fecha_actualizacion_jug',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='fecha_actualizacion_pru',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resultadomacro',
            name='fecha_actualizacion_resul',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='fecha_actualizacion_temp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokenpassword',
            name='fecha_actualizacion_tok',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_actualizacion_usu',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
