# Generated by Django 5.1.4 on 2025-06-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0009_alter_categoria_fecha_actualizacion_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='nombre_jug',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='primer_apellido_jug',
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='segundo_apellido_jug',
        ),
    ]
