# Generated by Django 5.1.4 on 2025-06-09 00:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0010_remove_jugador_nombre_jug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='fk_id_usu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entrenador', to=settings.AUTH_USER_MODEL),
        ),
    ]
