# Generated by Django 5.1.4 on 2025-06-10 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0011_alter_entrenador_fk_id_usu'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tip', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_tip', models.TextField(blank=True, null=True)),
                ('estado_tip', models.BooleanField(default=True)),
                ('fecha_creacion_tip', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_tip', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='fk_id_eva',
        ),
        migrations.CreateModel(
            name='ParametroEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prm', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_prm', models.TextField(blank=True, null=True)),
                ('estado_prm', models.BooleanField(default=True)),
                ('fecha_creacion_prm', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion_prm', models.DateTimeField(blank=True, null=True)),
                ('fk_tipo_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrenamientos.tipoevaluacion')),
            ],
        ),
        migrations.AddField(
            model_name='prueba',
            name='fk_id_tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Entrenamientos.tipoevaluacion'),
        ),
        migrations.DeleteModel(
            name='Evaluacion',
        ),
    ]
