# Generated by Django 5.1.4 on 2025-06-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrenamientos', '0012_tipoevaluacion_remove_prueba_fk_id_eva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleprueba',
            name='titulo_det',
        ),
        migrations.AddField(
            model_name='detalleprueba',
            name='fk_id_parametro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Entrenamientos.parametroevaluacion'),
        ),
    ]
